### ISSUE TITLE
CSS Truncation

### ISSUE THREAD

**Issue by PhishyFish** [PhishyFish/hubbub#8]
Truncate name (e.g. "verylonguserna...") if window size too small

**Comment by evhumphrey** [comment]
Awesome thanks for reminding me. To do this with CSS: 

```css
someElementSelector { 
  width: 100px; /* this would be the width of whatever element is holding the text */
  overflow: text-overflow; /* specifies how overflowing content is handled, like if text gets too long */
  white-space: nowrap; /* prevent text from wrapping to a new line */
  text-overflow: ellipsis; /* ... */
}
```

[W3 has a cool example of this.](https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-overflow)

Slack me if you have any questions!
